import React, { useState } from "react";
import jsPDF from "jspdf";
import "jspdf-autotable";
import axios from "axios";

const ReportGeneration = () => {
  const [loading, setLoading] = useState(false);
  const token = localStorage.getItem("token");

  const generatePDF = async () => {
    setLoading(true);
    try {
      const headers = { Authorization: `Bearer ${token}` };

      // 🔹 Fetch data from backend
      const [studentsRes, roomsRes, feesRes] = await Promise.all([
        axios.get("http://localhost:8080/api/students", { headers }),
        axios.get("http://localhost:8080/api/admin/rooms", { headers }),
        axios.get("http://localhost:8080/api/admin/fees", { headers }).catch(() => ({ data: [] })) // fallback if fees API not yet added
      ]);

      const students = studentsRes.data || [];
      const rooms = roomsRes.data || [];
      const fees = feesRes.data || [];

      // 🔹 Create new PDF
      const doc = new jsPDF();
      doc.setFontSize(18);
      doc.text("🏨 Hostel Management System Report", 14, 20);
      doc.setFontSize(12);
      doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 30);

      // -------------------------------
      // 🧍 Student Section
      // -------------------------------
      doc.setFontSize(14);
      doc.text("👨‍🎓 Student Details", 14, 45);

      if (students.length > 0) {
        doc.autoTable({
          startY: 50,
          head: [["Name", "Roll No", "Room No", "Department"]],
          body: students.map((s) => [
            s.name || "N/A",
            s.rollNumber || "N/A",
            s.roomNumber || "N/A",
            s.department || "N/A",
          ]),
        });
      } else {
        doc.text("No student records found.", 14, 55);
      }

      // -------------------------------
      // 🏠 Room Section
      // -------------------------------
      const nextY1 = doc.lastAutoTable?.finalY ? doc.lastAutoTable.finalY + 10 : 65;
      doc.text("🏠 Room Allocation", 14, nextY1);

      if (rooms.length > 0) {
        doc.autoTable({
          startY: nextY1 + 5,
          head: [["Room No", "Capacity"]],
          body: rooms.map((r) => [r.roomNo || "N/A", r.capacity || "N/A"]),
        });
      } else {
        doc.text("No room records found.", 14, nextY1 + 10);
      }

      // -------------------------------
      // 💰 Fee Section
      // -------------------------------
      const nextY2 = doc.lastAutoTable?.finalY ? doc.lastAutoTable.finalY + 10 : nextY1 + 30;
      doc.text("💰 Fee Payment Status", 14, nextY2);

      if (fees.length > 0) {
        doc.autoTable({
          startY: nextY2 + 5,
          head: [["Student", "Status", "Amount"]],
          body: fees.map((f) => [
            f.studentName || "N/A",
            f.status || "N/A",
            f.amount || "N/A",
          ]),
        });
      } else {
        doc.text("No fee records found.", 14, nextY2 + 10);
      }

      // -------------------------------
      // 📄 Footer
      // -------------------------------
      const footerY = doc.lastAutoTable?.finalY
        ? doc.lastAutoTable.finalY + 20
        : nextY2 + 30;
      doc.setFontSize(10);
      doc.text("Generated by Admin • Hostel Management System", 14, footerY);

      doc.save("Hostel_Report.pdf");
    } catch (err) {
      console.error("Error generating report:", err);
      alert("⚠️ Failed to generate report. Check if backend APIs are running.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-4">
      <h2>📊 Report Generation</h2>
      <p>Click below to generate a detailed report with live student, room, and fee details.</p>
      <button onClick={generatePDF} className="btn btn-success" disabled={loading}>
        {loading ? "Generating..." : "Generate PDF Report"}
      </button>
    </div>
  );
};

export default ReportGeneration;
